[2024-03-19 21:02:36,814: INFO: main: Welcome to the custom log]
[2024-03-20 17:18:48,249: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-20 17:18:48,259: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-20 17:20:15,946: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-20 17:20:15,947: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-20 17:37:57,799: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-03-20 17:37:57,810: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-20 17:37:57,812: INFO: common: created directory at: artifacts]
[2024-03-20 17:37:57,813: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-20 17:37:57,814: INFO: 723630791: Downloading data from https://drive.google.com/file/d/1enFGVoZhyqs81zUBAUfEmhhWqez1KFEA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-20 17:40:57,891: INFO: 723630791: Downloaded data from https://drive.google.com/file/d/1enFGVoZhyqs81zUBAUfEmhhWqez1KFEA/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-20 21:18:48,235: INFO: main: This is the main output]
[2024-03-20 22:48:12,016: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-20 22:48:12,020: ERROR: main: name 'yaml' is not defined]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "/home/oadebayo/PhD/DL_Benign_vs_Malignant_skin_tumour_with_keloid/src/cnnClassifier_benign_vs_malignant/pipeline/stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
  File "/home/oadebayo/PhD/DL_Benign_vs_Malignant_skin_tumour_with_keloid/src/cnnClassifier_benign_vs_malignant/config/configuration.py", line 16, in __init__
    self.config = read_yaml(config_filepath)
  File "/home/oadebayo/.local/lib/python3.8/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/home/oadebayo/PhD/DL_Benign_vs_Malignant_skin_tumour_with_keloid/src/cnnClassifier_benign_vs_malignant/utils/common.py", line 37, in read_yaml
    raise e
  File "/home/oadebayo/PhD/DL_Benign_vs_Malignant_skin_tumour_with_keloid/src/cnnClassifier_benign_vs_malignant/utils/common.py", line 31, in read_yaml
    content = yaml.safe_load(yaml_file)
NameError: name 'yaml' is not defined
